### PR TITLE
Bump WebdriverIO

### PR DESCRIPTION
**Pull request by FrederikBolding**
Bumps all WebdriverIO packages to latest including `esbuild`. Also bumps `puppeteer` for deduping reasons.

This PR includes a few patches, one to fix an issue that is yet to be fixed in WebdriverIO and one to fix a compatibility problem with `jest-util`.

This PR also pins `@types/node` to a specific v18 version to prevent type issues with streams. This should be investigated and fixed in the future.

Lastly this PR bumps `chromedriver` and the version of Chrome we use for E2E tests.

Hopefully this improves flakyness of E2E tests as WebdriverIO has had multiple updates that may alleviate our problems.

### CODE REVIEW

**Comment by FrederikBolding** [comment]
@metamaskbot update-pr

**Comment by FrederikBolding** [comment]
@SocketSecurity ignore fstream@1.0.12
@SocketSecurity ignore unzipper@0.10.14

FS access ok

@SocketSecurity ignore buffers@0.1.1
@SocketSecurity ignore chainsaw@0.1.0
@SocketSecurity ignore traverse@0.3.9

Required by geckodriver

@SocketSecurity ignore basic-ftp@5.0.3
@SocketSecurity ignore http-proxy-agent@7.0.0
@SocketSecurity ignore https-proxy-agent@7.0.1
@SocketSecurity ignore pac-proxy-agent@7.0.0
@SocketSecurity ignore socks-proxy-agent@8.0.1
@SocketSecurity ignore @tootallnate/quickjs-emscripten@0.23.0

Network access ok

**Review by Mrtenz — DISMISSED** [review]

**Comment by FrederikBolding** [comment]
@SocketSecurity ignore edgedriver@5.3.5
@SocketSecurity ignore geckodriver@4.2.0
@SocketSecurity ignore get-uri@6.0.1
@SocketSecurity ignore proxy-agent@6.3.0
@SocketSecurity ignore wait-port@1.0.4
@SocketSecurity ignore agent-base@7.1.0

Network access ok

@SocketSecurity ignore binary@0.3.0

Required by geckodriver

@SocketSecurity ignore locate-app@2.1.0

Used by wdio to track down browsers

@SocketSecurity ignore userhome@1.0.0
@SocketSecurity ignore web-streams-polyfill@3.2.1
@SocketSecurity ignore buffer-indexof-polyfill@1.0.2
@SocketSecurity ignore formdata-polyfill@1.0.2
@SocketSecurity ignore big-integer@1.6.51

"Unmaintained" packages, they look fine though and are used in dep trees of widely used packages.

**Comment by FrederikBolding** [comment]
@SocketSecurity ignore formdata-polyfill@4.0.10
@SocketSecurity ignore listenercount@1.0.1
@SocketSecurity ignore netmask@2.0.2

Required by geckodriver or otherwise used in widely used packages.

**Review by Mrtenz — APPROVED** [review]

**Pull request merged**
